[package]
name = "wasmedge_stable_diffusion_example"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmedge_stable_diffusion = {path="../rust"}
clap = { version = "4.4.6", features = ["cargo"] }
rand = "0.8"